# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uLearnApp', '0002_auto_20170314_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='categoru',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='uLearnApp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='sub_category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='uLearnApp.sub_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 11, 42, 42, 661397)),
        ),
    ]
