# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uLearnApp', '0003_auto_20170314_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='categoru',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 11, 47, 42, 57349)),
        ),
    ]
