# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uLearnApp', '0004_auto_20170314_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='lesson',
            field=models.ManyToManyField(to='uLearnApp.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 11, 53, 47, 866570)),
        ),
    ]
