# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uLearnApp', '0006_auto_20170321_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lectures',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uLearnApp.lectures'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 10, 19, 34, 673090)),
        ),
    ]
