# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uLearnApp', '0007_auto_20170321_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lectures',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uLearnApp.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 10, 26, 14, 751633)),
        ),
    ]
